services:
  postgres:
    image: "postgres:16.4-bullseye"
    ports: 
      - "5432:5432"
    expose:
      - 5432
    hostname: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-h", "localhost", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
